name: 'Scope for Gradle'
author: 'Daniel Rodriguez <@drodriguezhdez> | UndefinedLabs'
description: 'Automatically instruments and run your tests using Scope Java agent.'
inputs:
  dsn:
    description: 'Scope DSN'
    required: true
  run-tests:
    description: 'Flag to indicate if tests must be run. default: true'
    default: 'true'
    required: true
  command:
    description: 'Command to run your tests. default: ./gradlew test'
    default: './gradlew test'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'purple'